### ISSUE TITLE
incorrect pinout on github PDF?

### ISSUE THREAD

**Issue by TheRealDeathsneeze** [bigtreetech/BIGTREETECH-SKR-MINI-MZ#5]
Hi I am trying to configure klipper for this board, and I need the pinout for this board. The one listed on the github is not correct.

**Comment by foureight84** [comment]
Curious, Klipper has a generic cfg for this board https://github.com/KevinOConnor/klipper/blob/master/config/generic-bigtreetech-skr-mini-mz.cfg. I am going to switch over to klipper soon, are you having issues using their provided cfg?
